import type { Metadata } from "next";
import "./globals.css";
import PrelineScript from "app/libs/components/PrelineScript";
import Navbar from "app/libs/components/navigation/Navbar";
import Sidebar from "app/libs/components/navigation/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-100">
        <header>
          <Navbar />
          <Sidebar />
        </header>
        {children}
      </body>
      <PrelineScript />
    </html>
  );
}
